# Generated by Django 3.0.6 on 2020-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
